[pytest]
minversion = 6.0
addopts = -ra -q
testpaths = tests backtesting/service/tests
pythonpath = .
markers = 
    benchmark: marks tests as benchmark tests
    e2e: marks tests as end-to-end tests
