"""
Strategy Execution Service
This service manages the execution of strategies generated by the Blockly frontend.
"""

import logging
import importlib.util
from typing import Dict, Any

from nautilus_trader_engine.strategies.blockly_strategy_template import BlocklyStrategyTemplate

logger = logging.getLogger(__name__)

class StrategyExecutionService:
    """
    Dynamically loads and executes trading strategies.
    """

    def __init__(self):
        self.running_strategies: Dict[str, Any] = {}
        logger.info("StrategyExecutionService initialized.")

    def execute_strategy(self, strategy_code: str, strategy_id: str):
        """
        Executes a trading strategy in a sandboxed environment.
        """
        try:
            # Create a new module for the strategy
            spec = importlib.util.spec_from_loader(strategy_id, loader=None)
            strategy_module = importlib.util.module_from_spec(spec)

            # Execute the strategy code in the new module's namespace
            exec(strategy_code, strategy_module.__dict__)

            # Find the strategy class in the module
            StrategyClass = None
            for name, obj in strategy_module.__dict__.items():
                if isinstance(obj, type) and issubclass(obj, BlocklyStrategyTemplate) and obj is not BlocklyStrategyTemplate:
                    StrategyClass = obj
                    break
            
            if StrategyClass is None:
                raise ValueError("No valid strategy class found in the provided code.")

            # Create an instance of the strategy
            strategy_instance = StrategyClass()
            self.running_strategies[strategy_id] = strategy_instance
            logger.info(f"Successfully executed strategy {strategy_id}.")

            # In a real system, you would now start feeding data to the strategy's
            # on_tick() or on_bar() methods.
            # For now, we'll just log that the strategy is running.
            logger.info(f"Strategy {strategy_id} is now running.")

        except Exception as e:
            logger.error(f"Error executing strategy {strategy_id}: {e}")
            raise

    def stop_strategy(self, strategy_id: str):
        """
        Stops a running trading strategy.
        """
        if strategy_id in self.running_strategies:
            # In a real system, you would call a cleanup method on the strategy
            # instance to, for example, close any open positions.
            del self.running_strategies[strategy_id]
            logger.info(f"Strategy {strategy_id} has been stopped.")
        else:
            logger.warning(f"Strategy {strategy_id} is not currently running.")

    def get_running_strategies(self) -> Dict[str, Any]:
        """
        Returns a list of all currently running strategies.
        """
        return {strategy_id: strategy.__class__.__name__ for strategy_id, strategy in self.running_strategies.items()}