"""Strategy models for the algorithmic trading system.

This module provides data structures for trading strategies, strategy management,
and strategy execution tracking.
"""

import logging
from datetime import datetime
from typing import Dict, List, Optional, Any, Union, Callable
from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
import uuid

logger = logging.getLogger(__name__)


class StrategyType(Enum):
    """Strategy type enumeration."""
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    ARBITRAGE = "arbitrage"
    MARKET_MAKING = "market_making"
    TREND_FOLLOWING = "trend_following"
    PAIRS_TRADING = "pairs_trading"
    STATISTICAL_ARBITRAGE = "statistical_arbitrage"
    MACHINE_LEARNING = "machine_learning"
    CUSTOM = "custom"


class StrategyStatus(Enum):
    """Strategy status enumeration."""
    INACTIVE = "inactive"
    ACTIVE = "active"
    PAUSED = "paused"
    STOPPED = "stopped"
    ERROR = "error"
    BACKTESTING = "backtesting"
    PAPER_TRADING = "paper_trading"
    LIVE_TRADING = "live_trading"


class SignalType(Enum):
    """Signal type enumeration."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"
    REDUCE_LONG = "reduce_long"
    REDUCE_SHORT = "reduce_short"
    INCREASE_LONG = "increase_long"
    INCREASE_SHORT = "increase_short"


class SignalStrength(Enum):
    """Signal strength enumeration."""
    WEAK = "weak"
    MODERATE = "moderate"
    STRONG = "strong"
    VERY_STRONG = "very_strong"


@dataclass
class StrategyParameter:
    """Represents a strategy parameter."""
    name: str
    value: Any
    parameter_type: str  # "int", "float", "str", "bool", "list", "dict"
    description: Optional[str] = None
    min_value: Optional[Union[int, float]] = None
    max_value: Optional[Union[int, float]] = None
    allowed_values: Optional[List[Any]] = None
    is_required: bool = True
    is_optimizable: bool = False
    
    def validate(self) -> List[str]:
        """Validate parameter value."""
        errors = []
        
        if self.is_required and self.value is None:
            errors.append(f"Parameter '{self.name}' is required")
            return errors
        
        if self.value is None:
            return errors
        
        # Type validation
        if self.parameter_type == "int" and not isinstance(self.value, int):
            try:
                self.value = int(self.value)
            except (ValueError, TypeError):
                errors.append(f"Parameter '{self.name}' must be an integer")
        
        elif self.parameter_type == "float" and not isinstance(self.value, (int, float)):
            try:
                self.value = float(self.value)
            except (ValueError, TypeError):
                errors.append(f"Parameter '{self.name}' must be a number")
        
        elif self.parameter_type == "bool" and not isinstance(self.value, bool):
            if isinstance(self.value, str):
                self.value = self.value.lower() in ['true', '1', 'yes', 'on']
            else:
                errors.append(f"Parameter '{self.name}' must be a boolean")
        
        # Range validation
        if isinstance(self.value, (int, float)):
            if self.min_value is not None and self.value < self.min_value:
                errors.append(f"Parameter '{self.name}' must be >= {self.min_value}")
            if self.max_value is not None and self.value > self.max_value:
                errors.append(f"Parameter '{self.name}' must be <= {self.max_value}")
        
        # Allowed values validation
        if self.allowed_values and self.value not in self.allowed_values:
            errors.append(f"Parameter '{self.name}' must be one of {self.allowed_values}")
        
        return errors
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "name": self.name,
            "value": self.value,
            "parameter_type": self.parameter_type,
            "description": self.description,
            "min_value": self.min_value,
            "max_value": self.max_value,
            "allowed_values": self.allowed_values,
            "is_required": self.is_required,
            "is_optimizable": self.is_optimizable
        }


@dataclass
class TradingSignal:
    """Represents a trading signal generated by a strategy."""
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    strategy_id: str = ""
    symbol: str = ""
    signal_type: SignalType = SignalType.HOLD
    strength: SignalStrength = SignalStrength.MODERATE
    confidence: Decimal = Decimal('0.5')  # 0.0 to 1.0
    price: Optional[Decimal] = None
    quantity: Optional[Decimal] = None
    timestamp: datetime = field(default_factory=datetime.utcnow)
    
    # Signal context
    indicators: Dict[str, Any] = field(default_factory=dict)
    market_conditions: Dict[str, Any] = field(default_factory=dict)
    risk_metrics: Dict[str, Any] = field(default_factory=dict)
    
    # Execution details
    target_price: Optional[Decimal] = None
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    time_horizon: Optional[int] = None  # in minutes
    
    # Metadata
    reason: Optional[str] = None
    notes: Optional[str] = None
    tags: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    @property
    def is_entry_signal(self) -> bool:
        """Check if signal is an entry signal."""
        return self.signal_type in [SignalType.BUY, SignalType.SELL]
    
    @property
    def is_exit_signal(self) -> bool:
        """Check if signal is an exit signal."""
        return self.signal_type in [SignalType.CLOSE_LONG, SignalType.CLOSE_SHORT]
    
    @property
    def is_adjustment_signal(self) -> bool:
        """Check if signal is a position adjustment signal."""
        return self.signal_type in [
            SignalType.REDUCE_LONG, SignalType.REDUCE_SHORT,
            SignalType.INCREASE_LONG, SignalType.INCREASE_SHORT
        ]
    
    @property
    def is_bullish(self) -> bool:
        """Check if signal is bullish."""
        return self.signal_type in [SignalType.BUY, SignalType.INCREASE_LONG, SignalType.CLOSE_SHORT]
    
    @property
    def is_bearish(self) -> bool:
        """Check if signal is bearish."""
        return self.signal_type in [SignalType.SELL, SignalType.INCREASE_SHORT, SignalType.CLOSE_LONG]
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "signal_id": self.signal_id,
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "strength": self.strength.value,
            "confidence": float(self.confidence),
            "price": float(self.price) if self.price else None,
            "quantity": float(self.quantity) if self.quantity else None,
            "timestamp": self.timestamp.isoformat(),
            "indicators": self.indicators,
            "market_conditions": self.market_conditions,
            "risk_metrics": self.risk_metrics,
            "target_price": float(self.target_price) if self.target_price else None,
            "stop_loss": float(self.stop_loss) if self.stop_loss else None,
            "take_profit": float(self.take_profit) if self.take_profit else None,
            "time_horizon": self.time_horizon,
            "reason": self.reason,
            "notes": self.notes,
            "tags": self.tags,
            "metadata": self.metadata
        }


@dataclass
class StrategyPerformance:
    """Tracks strategy performance metrics."""
    strategy_id: str
    start_date: datetime
    end_date: Optional[datetime] = None
    
    # Trade statistics
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    
    # P&L metrics
    total_pnl: Decimal = Decimal('0')
    realized_pnl: Decimal = Decimal('0')
    unrealized_pnl: Decimal = Decimal('0')
    gross_profit: Decimal = Decimal('0')
    gross_loss: Decimal = Decimal('0')
    
    # Return metrics
    total_return: Decimal = Decimal('0')
    annualized_return: Decimal = Decimal('0')
    max_drawdown: Decimal = Decimal('0')
    current_drawdown: Decimal = Decimal('0')
    
    # Risk metrics
    sharpe_ratio: Optional[Decimal] = None
    sortino_ratio: Optional[Decimal] = None
    calmar_ratio: Optional[Decimal] = None
    volatility: Optional[Decimal] = None
    
    # Trade metrics
    win_rate: Decimal = Decimal('0')
    profit_factor: Optional[Decimal] = None
    average_win: Decimal = Decimal('0')
    average_loss: Decimal = Decimal('0')
    largest_win: Decimal = Decimal('0')
    largest_loss: Decimal = Decimal('0')
    
    # Execution metrics
    average_trade_duration: Optional[int] = None  # in minutes
    total_commission: Decimal = Decimal('0')
    total_fees: Decimal = Decimal('0')
    
    @property
    def net_pnl(self) -> Decimal:
        """Calculate net P&L after fees."""
        return self.total_pnl - self.total_commission - self.total_fees
    
    @property
    def loss_rate(self) -> Decimal:
        """Calculate loss rate."""
        return Decimal('100') - self.win_rate
    
    def update_metrics(self) -> None:
        """Update calculated metrics."""
        # Win rate
        if self.total_trades > 0:
            self.win_rate = (Decimal(self.winning_trades) / Decimal(self.total_trades)) * 100
        
        # Profit factor
        if self.gross_loss != 0:
            self.profit_factor = abs(self.gross_profit / self.gross_loss)
        
        # Average win/loss
        if self.winning_trades > 0:
            self.average_win = self.gross_profit / Decimal(self.winning_trades)
        if self.losing_trades > 0:
            self.average_loss = abs(self.gross_loss / Decimal(self.losing_trades))
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "strategy_id": self.strategy_id,
            "start_date": self.start_date.isoformat(),
            "end_date": self.end_date.isoformat() if self.end_date else None,
            "total_trades": self.total_trades,
            "winning_trades": self.winning_trades,
            "losing_trades": self.losing_trades,
            "total_pnl": float(self.total_pnl),
            "realized_pnl": float(self.realized_pnl),
            "unrealized_pnl": float(self.unrealized_pnl),
            "net_pnl": float(self.net_pnl),
            "gross_profit": float(self.gross_profit),
            "gross_loss": float(self.gross_loss),
            "total_return": float(self.total_return),
            "annualized_return": float(self.annualized_return),
            "max_drawdown": float(self.max_drawdown),
            "current_drawdown": float(self.current_drawdown),
            "sharpe_ratio": float(self.sharpe_ratio) if self.sharpe_ratio else None,
            "sortino_ratio": float(self.sortino_ratio) if self.sortino_ratio else None,
            "calmar_ratio": float(self.calmar_ratio) if self.calmar_ratio else None,
            "volatility": float(self.volatility) if self.volatility else None,
            "win_rate": float(self.win_rate),
            "loss_rate": float(self.loss_rate),
            "profit_factor": float(self.profit_factor) if self.profit_factor else None,
            "average_win": float(self.average_win),
            "average_loss": float(self.average_loss),
            "largest_win": float(self.largest_win),
            "largest_loss": float(self.largest_loss),
            "average_trade_duration": self.average_trade_duration,
            "total_commission": float(self.total_commission),
            "total_fees": float(self.total_fees)
        }


@dataclass
class Strategy:
    """Represents a trading strategy."""
    strategy_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    description: Optional[str] = None
    strategy_type: StrategyType = StrategyType.CUSTOM
    status: StrategyStatus = StrategyStatus.INACTIVE
    
    # Strategy configuration
    parameters: Dict[str, StrategyParameter] = field(default_factory=dict)
    symbols: List[str] = field(default_factory=list)
    timeframes: List[str] = field(default_factory=list)
    
    # Execution settings
    max_position_size: Optional[Decimal] = None
    max_daily_trades: Optional[int] = None
    risk_per_trade: Optional[Decimal] = None
    stop_loss_pct: Optional[Decimal] = None
    take_profit_pct: Optional[Decimal] = None
    
    # Portfolio allocation
    capital_allocation: Optional[Decimal] = None
    max_portfolio_risk: Optional[Decimal] = None
    
    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    started_at: Optional[datetime] = None
    stopped_at: Optional[datetime] = None
    
    # Performance tracking
    performance: Optional[StrategyPerformance] = None
    signals_generated: List[str] = field(default_factory=list)  # signal IDs
    
    # Code and implementation
    strategy_code: Optional[str] = None
    strategy_file: Optional[str] = None
    entry_function: Optional[str] = None
    exit_function: Optional[str] = None
    
    # Metadata
    author: Optional[str] = None
    version: str = "1.0.0"
    tags: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # Error handling
    last_error: Optional[str] = None
    error_count: int = 0
    
    @property
    def is_active(self) -> bool:
        """Check if strategy is active."""
        return self.status in [StrategyStatus.ACTIVE, StrategyStatus.PAPER_TRADING, StrategyStatus.LIVE_TRADING]
    
    @property
    def is_trading(self) -> bool:
        """Check if strategy is actively trading."""
        return self.status in [StrategyStatus.PAPER_TRADING, StrategyStatus.LIVE_TRADING]
    
    @property
    def is_backtesting(self) -> bool:
        """Check if strategy is backtesting."""
        return self.status == StrategyStatus.BACKTESTING
    
    def add_parameter(self, parameter: StrategyParameter) -> None:
        """Add a parameter to the strategy."""
        self.parameters[parameter.name] = parameter
        self.updated_at = datetime.utcnow()
    
    def get_parameter_value(self, name: str, default: Any = None) -> Any:
        """Get parameter value by name."""
        parameter = self.parameters.get(name)
        return parameter.value if parameter else default
    
    def set_parameter_value(self, name: str, value: Any) -> None:
        """Set parameter value by name."""
        if name in self.parameters:
            self.parameters[name].value = value
            self.updated_at = datetime.utcnow()
        else:
            raise ValueError(f"Parameter '{name}' not found")
    
    def validate_parameters(self) -> List[str]:
        """Validate all strategy parameters."""
        errors = []
        for parameter in self.parameters.values():
            errors.extend(parameter.validate())
        return errors
    
    def is_valid(self) -> bool:
        """Check if strategy configuration is valid."""
        return len(self.validate_parameters()) == 0
    
    def start(self) -> None:
        """Start the strategy."""
        if not self.is_valid():
            raise ValueError(f"Cannot start invalid strategy: {self.validate_parameters()}")
        
        self.status = StrategyStatus.ACTIVE
        self.started_at = datetime.utcnow()
        self.updated_at = self.started_at
        
        # Initialize performance tracking
        if not self.performance:
            self.performance = StrategyPerformance(
                strategy_id=self.strategy_id,
                start_date=self.started_at
            )
        
        logger.info(f"Strategy {self.strategy_id} ({self.name}) started")
    
    def stop(self, reason: Optional[str] = None) -> None:
        """Stop the strategy."""
        self.status = StrategyStatus.STOPPED
        self.stopped_at = datetime.utcnow()
        self.updated_at = self.stopped_at
        
        if self.performance:
            self.performance.end_date = self.stopped_at
        
        if reason:
            self.metadata["stop_reason"] = reason
        
        logger.info(f"Strategy {self.strategy_id} ({self.name}) stopped: {reason or 'No reason provided'}")
    
    def pause(self) -> None:
        """Pause the strategy."""
        if not self.is_active:
            return
        
        self.status = StrategyStatus.PAUSED
        self.updated_at = datetime.utcnow()
        
        logger.info(f"Strategy {self.strategy_id} ({self.name}) paused")
    
    def resume(self) -> None:
        """Resume the strategy."""
        if self.status != StrategyStatus.PAUSED:
            return
        
        self.status = StrategyStatus.ACTIVE
        self.updated_at = datetime.utcnow()
        
        logger.info(f"Strategy {self.strategy_id} ({self.name}) resumed")
    
    def handle_error(self, error: str) -> None:
        """Handle strategy error."""
        self.last_error = error
        self.error_count += 1
        self.status = StrategyStatus.ERROR
        self.updated_at = datetime.utcnow()
        
        logger.error(f"Strategy {self.strategy_id} error: {error}")
    
    def add_signal(self, signal: TradingSignal) -> None:
        """Add a generated signal to the strategy."""
        signal.strategy_id = self.strategy_id
        self.signals_generated.append(signal.signal_id)
        self.updated_at = datetime.utcnow()
    
    def get_strategy_summary(self) -> Dict[str, Any]:
        """Get strategy summary."""
        return {
            "strategy_id": self.strategy_id,
            "name": self.name,
            "description": self.description,
            "strategy_type": self.strategy_type.value,
            "status": self.status.value,
            "symbols": self.symbols,
            "timeframes": self.timeframes,
            "parameter_count": len(self.parameters),
            "signals_generated": len(self.signals_generated),
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "stopped_at": self.stopped_at.isoformat() if self.stopped_at else None,
            "author": self.author,
            "version": self.version,
            "error_count": self.error_count,
            "last_error": self.last_error
        }
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        summary = self.get_strategy_summary()
        summary.update({
            "parameters": {name: param.to_dict() for name, param in self.parameters.items()},
            "max_position_size": float(self.max_position_size) if self.max_position_size else None,
            "max_daily_trades": self.max_daily_trades,
            "risk_per_trade": float(self.risk_per_trade) if self.risk_per_trade else None,
            "stop_loss_pct": float(self.stop_loss_pct) if self.stop_loss_pct else None,
            "take_profit_pct": float(self.take_profit_pct) if self.take_profit_pct else None,
            "capital_allocation": float(self.capital_allocation) if self.capital_allocation else None,
            "max_portfolio_risk": float(self.max_portfolio_risk) if self.max_portfolio_risk else None,
            "performance": self.performance.to_dict() if self.performance else None,
            "strategy_code": self.strategy_code,
            "strategy_file": self.strategy_file,
            "entry_function": self.entry_function,
            "exit_function": self.exit_function,
            "tags": self.tags,
            "metadata": self.metadata
        })
        return summary


class StrategyManager:
    """Manages trading strategies."""
    
    def __init__(self):
        self.strategies: Dict[str, Strategy] = {}
        self.strategies_by_status: Dict[StrategyStatus, List[str]] = {}
        self.strategies_by_type: Dict[StrategyType, List[str]] = {}
        self.signals: Dict[str, TradingSignal] = {}
        self.logger = logging.getLogger(self.__class__.__name__)
    
    def add_strategy(self, strategy: Strategy) -> None:
        """Add a strategy to management."""
        if not strategy.is_valid():
            raise ValueError(f"Invalid strategy: {strategy.validate_parameters()}")
        
        self.strategies[strategy.strategy_id] = strategy
        
        # Index by status
        if strategy.status not in self.strategies_by_status:
            self.strategies_by_status[strategy.status] = []
        self.strategies_by_status[strategy.status].append(strategy.strategy_id)
        
        # Index by type
        if strategy.strategy_type not in self.strategies_by_type:
            self.strategies_by_type[strategy.strategy_type] = []
        self.strategies_by_type[strategy.strategy_type].append(strategy.strategy_id)
        
        self.logger.info(f"Strategy added: {strategy.strategy_id} ({strategy.name})")
    
    def get_strategy(self, strategy_id: str) -> Optional[Strategy]:
        """Get strategy by ID."""
        return self.strategies.get(strategy_id)
    
    def get_strategies_by_status(self, status: StrategyStatus) -> List[Strategy]:
        """Get all strategies with a specific status."""
        strategy_ids = self.strategies_by_status.get(status, [])
        return [self.strategies[sid] for sid in strategy_ids if sid in self.strategies]
    
    def get_strategies_by_type(self, strategy_type: StrategyType) -> List[Strategy]:
        """Get all strategies of a specific type."""
        strategy_ids = self.strategies_by_type.get(strategy_type, [])
        return [self.strategies[sid] for sid in strategy_ids if sid in self.strategies]
    
    def get_active_strategies(self) -> List[Strategy]:
        """Get all active strategies."""
        return [strategy for strategy in self.strategies.values() if strategy.is_active]
    
    def start_strategy(self, strategy_id: str) -> None:
        """Start a strategy."""
        strategy = self.get_strategy(strategy_id)
        if not strategy:
            raise ValueError(f"Strategy not found: {strategy_id}")
        
        strategy.start()
        self._update_strategy_status_index(strategy_id, strategy.status)
    
    def stop_strategy(self, strategy_id: str, reason: Optional[str] = None) -> None:
        """Stop a strategy."""
        strategy = self.get_strategy(strategy_id)
        if not strategy:
            raise ValueError(f"Strategy not found: {strategy_id}")
        
        strategy.stop(reason)
        self._update_strategy_status_index(strategy_id, strategy.status)
    
    def stop_all_strategies(self, reason: Optional[str] = None) -> List[str]:
        """Stop all active strategies."""
        stopped_strategies = []
        
        for strategy in self.get_active_strategies():
            self.stop_strategy(strategy.strategy_id, reason)
            stopped_strategies.append(strategy.strategy_id)
        
        return stopped_strategies
    
    def _update_strategy_status_index(self, strategy_id: str, new_status: StrategyStatus) -> None:
        """Update strategy status index."""
        # Remove from old status index
        for status, strategy_ids in self.strategies_by_status.items():
            if strategy_id in strategy_ids:
                strategy_ids.remove(strategy_id)
                break
        
        # Add to new status index
        if new_status not in self.strategies_by_status:
            self.strategies_by_status[new_status] = []
        self.strategies_by_status[new_status].append(strategy_id)
    
    def add_signal(self, signal: TradingSignal) -> None:
        """Add a trading signal."""
        self.signals[signal.signal_id] = signal
        
        # Add to strategy
        strategy = self.get_strategy(signal.strategy_id)
        if strategy:
            strategy.add_signal(signal)
    
    def get_signal(self, signal_id: str) -> Optional[TradingSignal]:
        """Get signal by ID."""
        return self.signals.get(signal_id)
    
    def get_signals_by_strategy(self, strategy_id: str) -> List[TradingSignal]:
        """Get all signals for a strategy."""
        return [signal for signal in self.signals.values() if signal.strategy_id == strategy_id]
    
    def get_recent_signals(self, hours: int = 24) -> List[TradingSignal]:
        """Get signals from the last N hours."""
        cutoff_time = datetime.utcnow() - datetime.timedelta(hours=hours)
        return [signal for signal in self.signals.values() if signal.timestamp >= cutoff_time]
    
    def get_manager_summary(self) -> Dict[str, Any]:
        """Get strategy manager summary."""
        status_counts = {}
        for status in StrategyStatus:
            status_counts[status.value] = len(self.get_strategies_by_status(status))
        
        type_counts = {}
        for strategy_type in StrategyType:
            type_counts[strategy_type.value] = len(self.get_strategies_by_type(strategy_type))
        
        return {
            "total_strategies": len(self.strategies),
            "active_strategies": len(self.get_active_strategies()),
            "total_signals": len(self.signals),
            "status_breakdown": status_counts,
            "type_breakdown": type_counts,
            "recent_signals_24h": len(self.get_recent_signals(24))
        }