"""
Base template for strategies generated by the Blockly frontend.
"""

from nautilus_trader.model.strategy import Strategy
from nautilus_trader_engine.indicators.consolidated_indicators import ConsolidatedIndicators


class BlocklyStrategyTemplate(Strategy):
    """
    A template for strategies generated by the Blockly frontend.
    The generated Python code will be injected into this class.
    """

    def on_tick(self):
        """
        This method will be overridden by the code generated from the Blockly workspace.
        """
        pass